---
- name: Configure Google DNS
  hosts: aws_ec2
  become: yes
  tasks:
    - name: Backup existing resolv.conf
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.bak
        remote_src: yes
        ignore_errors: yes
 
    - name: Add Google DNS to resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 8.8.8.8"
        state: present #present or absent