---
- name: Configure Google DNS
  hosts: aws_ec2
  become: true
  tasks:
    - name: Backup existing resolv.conf
      ansible.builtin.copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.bak
        remote_src: true
        mode: '0644'

    - name: Add Google DNS to resolv.conf
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: "google 8.8.8.8"
        state: present
    
      - name: Verify changes in resolv.conf
        ansible.builtin.shell: cat /etc/resolv.conf
        register: resolv_conf_content
 
    - name: Display updated resolv.conf
      ansible.builtin.debug:
        msg: "{{ resolv_conf_content.stdout }}"
